apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-cast-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ if eq $.Values.environment "prod" }}{{ .host }}{{ else }}{{ $.Values.environment }}.{{ .host }}{{ end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.nginx.name }}
                port:
                  number: {{ $.Values.nginx.port }}
          {{- end }}
    {{- end }}

