apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.movieService.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.movieService.storage | default "2Gi" }}
