apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
spec:
  # type: NodePort
  selector:
    app: {{ .Values.nginx.name }}
  ports:
  - port: {{ .Values.nginx.port }}
    targetPort: {{ .Values.nginx.port }}
   # nodePort: 30007

