apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: {{ .Values.nginx.image }}:{{ .Values.nginx.tag }}
        ports:
        - containerPort: {{ .Values.nginx.port }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Values.nginx.name }}-config
