
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  - name: registry-secret #Ajoute l' image pull secret pour faire un  pull kubernetes image a partir du registre docker Hub


nginx:
  name: nginx
  port: 8080
  replicas: 1
  image: nginx
  tag: ""
  storage: 2Gi

movieService:
  name: movie-service
  replicas: 1
  port: 8000
  servicePort: 8001
  image: ""
  tag: ""
  storage: 
    size: 2Gi
    configMountPath: "app/data" # je ne dois pas stocker en pvc  dans app directement. ça ecrase le contenu de app.

  db:
    name: movie-db
    replicas: 1
    user: movie_db_username
    password: movie_db_password
    dbName: movie_db_dev
    port: 5432
    image: nginx
    tag: ""
    storage: 2Gi

castService:
  name: cast-service
  replicas: 1
  port: 8000
  servicePort: 8002
  image: nginx
  tag: ""
  storage: 
    size: 2Gi
    configMountPath: "app/data" # je ne dois pas stocker en pvc  dans app directement. ça ecrase le contenu de app.

  db:
    name: cast-db
    replicas: 1
    user: cast_db_username
    password: cast_db_password
    dbName: cast_db_dev
    port: 5432
    image: nginx
    tag: ""
    storage: 2Gi


environment: dev

ingress:
  hosts:
    - host: movie-cast.ip-ddns.com
      paths:
        - path: /api/v1/casts
          pathType: Prefix
